title: Junxiao Guo | Home
description: > # this means to ignore newlines until "baseurl:"
  Junxiao Guo's blog
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "ghostian.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Junxiao Guo # add your name
author-img: jx-guo.jpeg # add your photo
about-author: Master Student of Electrical & Computer Engineering at Carnegie Mellon University # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: ghostian # add your Github handle
social-linkedin: jx95# add your Linkedin handle
social-email: guojunxiao2010@outlook.com# add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock","vendor"]
